config/routes.rb
Veggieout::Application.routes.draw do
  get "vegetable/create"

  get "fruit/create"

  get "activiy/create"

  get "relaxation/create"

  get "sleep/create"

  get "welcome/index"

  get "welcome/about"

  
  devise_for :users

  resources :users, only: [:show, :index] do
    get :timeline, on: :member # /users/:id/timeline
    get :data, on: :member
    # get :timeline, on: :collection # /users/timeline
  end # create a route for users#show

  resources :vegetables, only: [:create]

  resources :fruits, only: [:create]

  resources :activities, only: [:create]

  resources :relaxations, only: [:create]

  resources :sleeps, only: [:create]

  root to: 'welcome#index'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :calories_burned, :count, :name
end

app/models/fruit.rb
class Fruit < ActiveRecord::Base
  attr_accessible :count, :name
end

app/models/relaxation.rb
class Relaxation < ActiveRecord::Base
  attr_accessible :count, :name
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
  attr_accessible :count
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar
  # attr_accessible :title, :body
  mount_uploader :avatar, AvatarUploader

  has_many :vegetables
  has_many :fruits
  has_many :activities
  has_many :relaxations
  has_many :sleeps

  def vegetable_data_from(days_ago)
    days_ago.downto(1).map do |i|
      vegetables.where("created_at > ? AND created_at < ?", i.days.ago.beginning_of_day, i.days.ago.end_of_day).count
    end
  end

  def fruit_data_from(days_ago)
    days_ago.downto(1).map do |i|
      fruits.where("created_at > ? AND created_at < ?", i.days.ago.beginning_of_day, i.days.ago.end_of_day).count
    end
  end

  def activity_data_from(days_ago)
    days_ago.downto(1).map do |i|
      activities.where("created_at > ? AND created_at < ?", i.days.ago.beginning_of_day, i.days.ago.end_of_day).count
    end
  end

  def relaxation_data_from(days_ago)
    days_ago.downto(1).map do |i|
      relaxations.where("created_at > ? AND created_at < ?", i.days.ago.beginning_of_day, i.days.ago.end_of_day).count
    end
  end

  def sleep_data_from(days_ago)
    days_ago.downto(1).map do |i|
      sleeps.where("created_at > ? AND created_at < ?", i.days.ago.beginning_of_day, i.days.ago.end_of_day).count
    end
  end

  def summary_data(options={})
      if options[:interval] == "week"
        labels = 7.downto(1).map do |i|
          i.days.ago.strftime("%a")
        end

        {
          labels: labels,
          datasets: [
            {
              data: vegetable_data_from(7)
            },
            {
              data: fruit_data_from(7)
            },
            {
              data: activity_data_from(7)
            },
            {
              data: relaxation_data_from(7)
            },
            {
              data: sleep_data_from(7)
            }
          ]
        }
      elsif options[:interval] == "month"
        labels = 30.downto(1).map do |i|
            i.days.ago.strftime("%a")
          end

          {
            labels: labels,
            datasets: [
              {
                data: vegetable_data_from(30)
              },
              {
                data: fruit_data_from(30)
              },
              {
                data: activity_data_from(30)
              },
              {
                data: relaxation_data_from(30)
              },
              {
                data: sleep_data_from(30)
              }
            ]
          }
      elsif options[:interval] == "year"
        labels = 365.downto(1).map do |i|
            i.days.ago.strftime("%a")
          end

          {
            labels: labels,
            datasets: [
              {
                data: vegetable_data_from(365)
              },
              {
                data: fruit_data_from(365)
              },
              {
                data: activity_data_from(365)
              },
              {
                data: relaxation_data_from(365)
              },
              {
                data: sleep_data_from(365)
              }
            ]
          }
      end
  end
end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
  attr_accessible :count, :name
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def create
  	activity = current_user.activities.new(params[:activity])
  	activity.save!

  	redirect_to user_path(current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  def create
  	fruit = current_user.fruits.new(params[:fruit])
  	fruit.save!

  	redirect_to user_path(current_user)
  end
end

app/controllers/relaxations_controller.rb
class RelaxationsController < ApplicationController
  def create
  	relaxation = current_user.relaxations.new(params[:relaxation])
  	relaxation.save!

  	redirect_to user_path(current_user)
  end
end

app/controllers/sleeps_controller.rb
class SleepsController < ApplicationController
  def create
  	sleep = current_user.sleeps.new(params[:sleep])
  	sleep.save!

  	redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])  
    @vegetables = current_user.vegetables.where("created_at > ?", Time.now.beginning_of_day)
    @fruits = current_user.fruits .where("created_at > ?", Time.now.beginning_of_day)
    @activities = current_user.activities .where("created_at > ?", Time.now.beginning_of_day)
    @relaxations = current_user.relaxations .where("created_at > ?", Time.now.beginning_of_day)
    @sleeps = current_user.sleeps .where("created_at > ?", Time.now.beginning_of_day)
  end

  def index
  	@users = User.all
  end

  def data
  	render json: current_user.summary_data(interval: params[:interval]).to_json
  end

end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
  # POST /vegetables => VegetablesController#create
  def create
  	vegetable = current_user.vegetables.new(params[:vegetable])
  	vegetable.save!

  	redirect_to user_path(current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VeggieOut</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Luckiest+Guy' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
    	<div class="container">
    		<ul class="nav">
          <li><%= link_to "VeggieOut", root_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <div class="pull-right user-info">
            <% if current_user %>
              <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
              Hello <%= link_to (current_user.name || current_user.email), current_user %>!
              <%= link_to edit_user_registration_path, class: 'btn btn-mini' do %>
                <i class="icon-user"> </i>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do %>
                <i class="icon-share-alt"> </i>
              <% end %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %> or 
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
          </div>
        </ul>
      </div>
    </div>

  	<% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/_user.html.erb
<div class="media">
  <%= link_to user, class: 'pull-left' do %>
    <%= image_tag(user.avatar.profile.url) if user.avatar? %>
  <% end %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to user.name, user_path(user) %>
    </h4>
  </div>
</div>

app/views/users/index.html.erb
<div class="container content">
	<h1> Users </h1>
	<% @users.each do |user| %>
	  <%= render partial: "user", locals: {user: user} %>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="container-fluid content">
  <div class="row-fluid">
    <div class="span4 first-section">
      <div class="media">
        <div class="pull-center">
          <% if @user.avatar? %>
            <%= image_tag @user.avatar.url %>
          <% end %>
          <h2 class="media-body"><%= @user.name %></h2>
        </div>

        <canvas id="summary-chart"></canvas>

         <div class="btn-group">
          <button type="button" class="btn btn-default" id="week-button">Week</button>
          <button type="button" class="btn btn-default" id="month-button">Month</button>
          <button type="button" class="btn btn-default" id="year-button">Year</button>
        </div>

         
      </div>
    </div>


    <div class="span8 second-section">
      <h3> Vegetables consumed </h3>
      <div class="progress percentage"> 
        <div class="bar" style="width: <%= @vegetables.sum('count').to_f / 10.0 * 100 %>%"></div><span class="numbar"> <%= @vegetables.sum('count').to_f / 10.0 * 100 %>% </span>
      </div>
      <% if current_user == @user %>
        <%= form_for Vegetable.new, html: { class: "form-inline" } do |form| %>
          <%= form.text_field :name, class: "form-control", placeholder: "name" %>
          <%= form.number_field :count, class: "input-small", placeholder: "count" %>
          <%= form.submit :add, class: "btn btn-default" %>
        <% end %> 
      <% end %>
      
    

      <h3> Fruit consumed </h3>
       <div class="progress percentage"> 
        <div class="bar" style="width: <%= @fruits.sum('count').to_f / 10.0 * 100 %>%"></div><span class="numbar"> <%= @fruits.sum('count').to_f / 10.0 * 100 %>% </span>
      </div>

      <% if current_user == @user %>
        <%= form_for Fruit.new, html: { class: "form-inline" } do |form| %>
          <%= form.text_field :name, class: "form-control", placeholder: "name" %>
          <%= form.number_field :count, class: "input-small", placeholder: "count" %>
          <%= form.submit :add, class: "btn btn-default" %>
        <% end %> 
      <% end %>
     

   
      <h3> Activities </h3>
      <div class="progress percentage"> 
        <div class="bar" style="width: <%= @activities.sum('count').to_f / 60.0 * 100 %>%"></div><span class="numbar"> <%= @activities.sum('count').to_f / 10.0 * 100 %>% </span>
      </div>
      <% if current_user == @user %>
        <%= form_for Activity.new, html: { class: "form-inline" } do |form| %>
          <%= form.text_field :name, class: "form-control", placeholder: "name" %>
          <%= form.number_field :count, class: "input-small", placeholder: "number of minutes" %>
          <%= form.submit :add, class: "btn btn-default" %>
        <% end %> 
      <% end %>
      
  
    <h3> Relaxtion </h3>
     <div class="progress percentage"> 
      <div class="bar" style="width: <%= @relaxations.sum('count').to_f / 60.0 * 100 %>%"></div><span class="numbar"> <%= @relaxations.sum('count').to_f / 10.0 * 100 %>% </span>
    </div>
    <% if current_user == @user %>
      <%= form_for Relaxation.new, html: { class: "form-inline" } do |form| %>
        <%= form.text_field :name, class: "form-control", placeholder: "form of relaxation" %>
        <%= form.number_field :count, class: "input-small", placeholder: "number of minutes" %>
        <%= form.submit :add, class: "btn btn-default" %>
      <% end %> 
    <% end %>
   

     <h3> Hours slept </h3>
    <div class="progress percentage"> 
      <div class="bar" style="width: <%= @sleeps.sum('count').to_f / 10.0 * 100 %>%"></div><span class="numbar"> <%= @sleeps.sum('count').to_f / 10.0 * 100 %>% </span>
    </div>  
     <% if current_user == @user %>
      <%= form_for Sleep.new, html: { class: "form-inline" } do |form| %>
        <%= form.text_field :count, class: "form-control", placeholder: "number of hours" %>
        <%= form.submit :add, class: "btn btn-default" %>
      <% end %> 
    <% end %>
  </div>
</div>

app/views/users/timeline.html.erb
 <h3>Timeline</h3>
 <div class="btn-group">
  <button type="button" class="btn btn-default" id="week-button">Week</button>
  <button type="button" class="btn btn-default" id="month-button">Month</button>
  <button type="button" class="btn btn-default" id="year-button">Year</button>
</div>

 <canvas id="summary-chart"></canvas>

app/views/welcome/about.html.erb
<div class="container content">
	<h1>About VeggieOut</h1>
	<p>Created by JCP</p>
</div>

app/views/welcome/index.html.erb
<div class="container content">
  <div class="hero-unit">
  	<h1 class="text-left">Welcome to <strong class="logo">VeggieOut!</strong></h1>

    <div class="space"></div>

  	<p class="text-right">
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-inverse' %> or 
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-inverse' %> today!
    </p>
  </div>

  <div class="row">
    <div class="span6">
      <h2>Track your healthy habits</h2>
      <p>We make it easy for you to know how well you are doing. Think <br>of us as your personal checklist.</p>
    </div>
  
    <div class="span6" id="monitor">
      <h2>Monitor your improvments</h2>
      <p>Curious how much you've improved over the week? Month? Our <br> data analytics make it simple to review your progress over time.</p>
    </div>
  </div>
</div>